version: '3.1'

services:
  redis:
    image: redis:7.0.7
    expose:
      - 6379

  postgres:
    image: postgres:15.1-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=some_secret
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      retries: 10

  application:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: application
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=some_secret
      - POSTGRES_DB=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started