version: '3.1'

services:
  redis:
    image: redis:7.0.7
    expose:
      - 6379

  postgres:
    image: postgres:15.1-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=some_secret
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      retries: 10

  web:
    image: nginx:1.23.3-alpine
    depends_on:
      - app
    volumes:
    - ./nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
    - 3000:3000

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=some_secret
      - POSTGRES_DB=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - 1234
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started